### PR TITLE
cases don't need braces xD

### PR DESCRIPTION
**Pull request by xBeastMode**

### CODE REVIEW

**Comment by Gamecrafter** [comment]
@xBeastMode Why did you wrap the one line of code with an extra pair of parentheses? You don't need it.

**Comment by thebigsmileXD** [comment]
The case statement i used was correct. The braces replace the break. I always use them this way.

**Comment by xBeastMode** [comment]
@Gamecrafter because I see map modder do it.

**Comment by Gamecrafter** [comment]
@xBeastMode Monkey see monkey do? :stuck_out_tongue: You changed it to `if(($sender->hasPermission("dynmap.cmd")))`, when it already worked fine as `if($sender->hasPermission("dynmap.cmd"))`.

**Comment by thebigsmileXD** [comment]
@Gamecrafter Actually.. it didn't, after that it worked

**Comment by Gamecrafter** [comment]
@thebigsmileXD That's because he removed the extra braces you put, not the one I was talking about. :P

**Comment by thebigsmileXD** [comment]
Nope.. I updated the repo. And i just only removed these brackets

**Pull request merged**
